/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Account': RouteRecordInfo<'/Account', '/Account', Record<never, never>, Record<never, never>>,
    '/bootstrap/2/111': RouteRecordInfo<'/bootstrap/2/111', '/bootstrap/2/111', Record<never, never>, Record<never, never>>,
    '/bootstrap/2/出貨單': RouteRecordInfo<'/bootstrap/2/出貨單', '/bootstrap/2/出貨單', Record<never, never>, Record<never, never>>,
    '/bootstrap/2/出貨單eng': RouteRecordInfo<'/bootstrap/2/出貨單eng', '/bootstrap/2/出貨單eng', Record<never, never>, Record<never, never>>,
    '/bootstrap/2/員工資料表': RouteRecordInfo<'/bootstrap/2/員工資料表', '/bootstrap/2/員工資料表', Record<never, never>, Record<never, never>>,
    '/bootstrap/2/員工資料表_Query': RouteRecordInfo<'/bootstrap/2/員工資料表_Query', '/bootstrap/2/員工資料表_Query', Record<never, never>, Record<never, never>>,
    '/bootstrap/2/產品資料表': RouteRecordInfo<'/bootstrap/2/產品資料表', '/bootstrap/2/產品資料表', Record<never, never>, Record<never, never>>,
    '/bootstrap/2/報價單': RouteRecordInfo<'/bootstrap/2/報價單', '/bootstrap/2/報價單', Record<never, never>, Record<never, never>>,
    '/bootstrap/2/資源預約2': RouteRecordInfo<'/bootstrap/2/資源預約2', '/bootstrap/2/資源預約2', Record<never, never>, Record<never, never>>,
    '/bootstrap/2/應徵人員基本資料表': RouteRecordInfo<'/bootstrap/2/應徵人員基本資料表', '/bootstrap/2/應徵人員基本資料表', Record<never, never>, Record<never, never>>,
    '/bootstrap/2/form': RouteRecordInfo<'/bootstrap/2/form', '/bootstrap/2/form', Record<never, never>, Record<never, never>>,
    '/bootstrap/SOLUTION1/111': RouteRecordInfo<'/bootstrap/SOLUTION1/111', '/bootstrap/SOLUTION1/111', Record<never, never>, Record<never, never>>,
    '/bootstrap/SOLUTION1/出貨單a': RouteRecordInfo<'/bootstrap/SOLUTION1/出貨單a', '/bootstrap/SOLUTION1/出貨單a', Record<never, never>, Record<never, never>>,
    '/bootstrap/SOLUTION1/出貨單eng': RouteRecordInfo<'/bootstrap/SOLUTION1/出貨單eng', '/bootstrap/SOLUTION1/出貨單eng', Record<never, never>, Record<never, never>>,
    '/bootstrap/SOLUTION1/半成品': RouteRecordInfo<'/bootstrap/SOLUTION1/半成品', '/bootstrap/SOLUTION1/半成品', Record<never, never>, Record<never, never>>,
    '/bootstrap/SOLUTION1/客戶訂單': RouteRecordInfo<'/bootstrap/SOLUTION1/客戶訂單', '/bootstrap/SOLUTION1/客戶訂單', Record<never, never>, Record<never, never>>,
    '/bootstrap/SOLUTION1/客戶資料表': RouteRecordInfo<'/bootstrap/SOLUTION1/客戶資料表', '/bootstrap/SOLUTION1/客戶資料表', Record<never, never>, Record<never, never>>,
    '/bootstrap/SOLUTION1/客戶資料表VIEW': RouteRecordInfo<'/bootstrap/SOLUTION1/客戶資料表VIEW', '/bootstrap/SOLUTION1/客戶資料表VIEW', Record<never, never>, Record<never, never>>,
    '/bootstrap/SOLUTION1/派車單3': RouteRecordInfo<'/bootstrap/SOLUTION1/派車單3', '/bootstrap/SOLUTION1/派車單3', Record<never, never>, Record<never, never>>,
    '/bootstrap/SOLUTION1/員工資料表': RouteRecordInfo<'/bootstrap/SOLUTION1/員工資料表', '/bootstrap/SOLUTION1/員工資料表', Record<never, never>, Record<never, never>>,
    '/bootstrap/SOLUTION1/產品資料表': RouteRecordInfo<'/bootstrap/SOLUTION1/產品資料表', '/bootstrap/SOLUTION1/產品資料表', Record<never, never>, Record<never, never>>,
    '/bootstrap/SOLUTION1/測試RV': RouteRecordInfo<'/bootstrap/SOLUTION1/測試RV', '/bootstrap/SOLUTION1/測試RV', Record<never, never>, Record<never, never>>,
    '/bootstrap/SOLUTION1/跑步紀錄': RouteRecordInfo<'/bootstrap/SOLUTION1/跑步紀錄', '/bootstrap/SOLUTION1/跑步紀錄', Record<never, never>, Record<never, never>>,
    '/bootstrap/SOLUTION1/進貨標籤': RouteRecordInfo<'/bootstrap/SOLUTION1/進貨標籤', '/bootstrap/SOLUTION1/進貨標籤', Record<never, never>, Record<never, never>>,
    '/bootstrap/SOLUTION1/datapanel': RouteRecordInfo<'/bootstrap/SOLUTION1/datapanel', '/bootstrap/SOLUTION1/datapanel', Record<never, never>, Record<never, never>>,
    '/bootstrap/SOLUTION1/order': RouteRecordInfo<'/bootstrap/SOLUTION1/order', '/bootstrap/SOLUTION1/order', Record<never, never>, Record<never, never>>,
    '/ChangePassword': RouteRecordInfo<'/ChangePassword', '/ChangePassword', Record<never, never>, Record<never, never>>,
    '/Flow': RouteRecordInfo<'/Flow', '/Flow', Record<never, never>, Record<never, never>>,
    '/Logon': RouteRecordInfo<'/Logon', '/Logon', Record<never, never>, Record<never, never>>,
    '/main/AgentSetting': RouteRecordInfo<'/main/AgentSetting', '/main/AgentSetting', Record<never, never>, Record<never, never>>,
    '/Main': RouteRecordInfo<'/Main', '/Main', Record<never, never>, Record<never, never>>,
    '/MyfavorModal': RouteRecordInfo<'/MyfavorModal', '/MyfavorModal', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/SignatureModal': RouteRecordInfo<'/SignatureModal', '/SignatureModal', Record<never, never>, Record<never, never>>,
  }
}
